[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
max_time_assert = "7E7nvzfrapNcHYDeBjyHK7YnGo1w1PqSUNfeLPtodJxc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/posley3302_06/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
